server:
  port: 8080

spring:
  # 1. 数据库 (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3307/tyy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000ms
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/?authSource=admin

  # 6. Security
  security:
    user:
      name: admin
      password: 123456
  jackson: # 日期格式
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      # 空值处理
      default-property-inclusion: non_null
jwt:
  secret: "JWT-SECRET-KEY-1234567890-ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 86400000  # 24小时（毫秒）

# 7. MyBatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


springdoc:
  swagger-ui:
    path: /swagger-ui # 修改为正确的路径
    enabled: true
  api-docs:
    path: /v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  prometheus:
    metrics:
      export:
        enabled: true